name: odssm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - prefect=1.4, <2
  - cloudpickle
  - ansible-core
  - terraform
  - requests
  - dnspython
  - boto3
  - dunamai
  - s3fs
