---

collections:
- name: ansible.posix
  version: 1.5.2

- name: community.docker
  version: 3.4.4

- name: community.general
  version: 6.6.0

- name: amazon.aws
  version: 5.4.0

- name: community.aws
  version: 5.4.0
